export const FETCH_STUDY_GROUP_LIST_TYPES = {
  REQUEST: "FETCH_STUDY_GROUP_LIST_REQUEST",
  RECEIVE: "FETCH_STUDY_GROUP_LIST_RECEIVE",
  FAILURE: "FETCH_STUDY_GROUP_LIST_FAILURE",
};

export const EDITOR_GLOBAL = "EDITOR_GLOBAL";
export const SET_IMAGE = "SET_IMAGE";

